### ISSUE TITLE
, I am Divyam Dubey , undergrad 3rd year computer science student. I had worked with full stack technologies like reactjs, nextjs, express js. I am in need of internship for the same, so that I can learn from the experience and able to buy a coffee on my own. I am waiting for your reply. 
Sorry if it was way too informal.
Any help from you is really appreciated.

### ISSUE THREAD

**Issue by divyam-07** [lunaticscode/freeground-back#1]

**Comment by lunaticscode** [comment]
Hi, Thanks for looking at my repository, and I thought how can I help you.

So, How about I help you with your building demo-project and code-review for this project?
(It's the way I comment on your building process and code(Javascript, React, NextJS, NodeJS, Express))

**Comment by lunaticscode** [comment]
Hi, Thanks for looking at my repository, and I thought how can I help you.

So, How about I help you with your building demo-project and code-review
for this project?
(It's the way I comment on your building process and code(Javascript,
React, NextJS, NodeJS, Express))

2022년 9월 22일 (목) 오전 3:33, Divyam Dubey ***@***.***>님이 작성:
